// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCzZSvnti4OhgEE-KEBwEG9uwpUkzbw8',
    appId: '1:521224848312:web:7f46ea0bb1aa6b0294c54d',
    messagingSenderId: '521224848312',
    projectId: 'hair-treat-drochia',
    authDomain: 'hair-treat-drochia.firebaseapp.com',
    storageBucket: 'hair-treat-drochia.firebasestorage.app',
    measurementId: 'G-61K9XRFVZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoW-avwoJ6wRIqQzorGtDYbJnIRBoNW-k',
    appId: '1:521224848312:android:1c86cc6f99187c2594c54d',
    messagingSenderId: '521224848312',
    projectId: 'hair-treat-drochia',
    storageBucket: 'hair-treat-drochia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQy2llvysUQfXVeF9iEOkI9EH4d_pFL0',
    appId: '1:521224848312:ios:18ea2dac342c95c694c54d',
    messagingSenderId: '521224848312',
    projectId: 'hair-treat-drochia',
    storageBucket: 'hair-treat-drochia.firebasestorage.app',
    iosBundleId: 'com.example.hairTreat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiQy2llvysUQfXVeF9iEOkI9EH4d_pFL0',
    appId: '1:521224848312:ios:18ea2dac342c95c694c54d',
    messagingSenderId: '521224848312',
    projectId: 'hair-treat-drochia',
    storageBucket: 'hair-treat-drochia.firebasestorage.app',
    iosBundleId: 'com.example.hairTreat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFCzZSvnti4OhgEE-KEBwEG9uwpUkzbw8',
    appId: '1:521224848312:web:f637c7e73163910e94c54d',
    messagingSenderId: '521224848312',
    projectId: 'hair-treat-drochia',
    authDomain: 'hair-treat-drochia.firebaseapp.com',
    storageBucket: 'hair-treat-drochia.firebasestorage.app',
    measurementId: 'G-NCY325W7GE',
  );
}
